from __future__ import annotations

from copy import deepcopy
from typing import Any

ROLEPLAY_V2_SCHEMA_VERSION = 1

ROLEPLAY_V2_CANONICAL_SOURCE_CONTAINER_KINDS = [
    'novel_project',
    'storyline',
    'story_session',
]

ROLEPLAY_V2_CANONICAL_ENTITY_KINDS = [
    'character',
    'world',
    'universe',
    'region',
    'city',
    'location',
    'organization',
    'scenario',
    'artifact',
    'ritual',
    'cycle',
    'creature',
    'legend',
    'pack',
]

ROLEPLAY_V2_CANONICAL_MEMORY_TYPES = [
    'identity_fact',
    'world_fact',
    'semantic_fact',
    'canon_guard',
    'callback_anchor',
    'relationship_belief',
    'shared_memory',
    'episodic_event',
    'location_state',
    'scene_pressure',
    'story_hook',
    'self_belief',
    'goal',
    'secret',
    'voice_rule',
]

ROLEPLAY_V2_CANONICAL_ENTITY_MAP: dict[str, dict[str, Any]] = {
    'character': {
        'display_name': 'Character',
        'category': 'actor',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_world_graph', 'age_timeline', 'appearance_presence',
            'personality_behavior_speech', 'beliefs_morality', 'goals_desire_fear_wounds',
            'family_romance_social_history', 'secrets_lies_hidden_truth', 'skills_abilities_power',
            'affiliations_possessions_systems', 'relationships', 'story_roleplay_use', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'role_tier', 'species_or_race', 'appearance_summary',
            'personality_overview', 'speech_style', 'belief_overview', 'personal_goals',
            'core_desires', 'core_fears', 'wounds_fears_triggers', 'story_hooks',
            'scene_use_overview', 'memory_anchors', 'sensory_anchors',
        ],
        'authoring_field_paths': [
            'fields.identity.role_tier',
            'fields.identity.species_or_race',
            'fields.appearance_presence.appearance_summary',
            'fields.personality_behavior_speech.personality_overview',
            'fields.personality_behavior_speech.speech_style',
            'fields.beliefs_morality.belief_overview',
            'fields.goals_desire_fear_wounds.personal_goals',
            'fields.goals_desire_fear_wounds.core_desires',
            'fields.goals_desire_fear_wounds.core_fears',
            'fields.goals_desire_fear_wounds.wounds_fears_triggers',
            'fields.story_roleplay_use.story_hooks',
            'fields.story_roleplay_use.scene_use_overview',
            'memory_hints.memory_anchors',
            'memory_hints.sensory_anchors',
        ],
        'link_ownership': {
            'scope': [
                'origin_world_id', 'current_world_id', 'origin_region_id', 'current_region_id',
                'origin_city_id', 'current_city_id', 'origin_location_id', 'current_location_id',
            ],
            'related': ['organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'legend_ids', 'scenario_ids'],
        },
        'edge_sections': ['fields.relationships'],
        'derived_reverse_links': ['world.characters', 'organization.members', 'artifact.holders', 'scenario.cast'],
        'runtime_surface': {
            'identity': ['summary', 'species_or_race', 'appearance_summary', 'personality_overview', 'speech_style'],
            'behavior': ['belief_overview', 'personal_goals', 'core_desires', 'core_fears', 'wounds_fears_triggers'],
            'hooks': ['story_hooks', 'scene_use_overview'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'role_tier', 'species_or_race'],
            'fragment_candidates': [
                'summary', 'appearance_summary', 'personality_overview', 'speech_style',
                'belief_overview', 'personal_goals', 'core_desires', 'core_fears',
                'wounds_fears_triggers', 'story_hooks', 'scene_use_overview',
                'memory_anchors', 'sensory_anchors',
            ],
            'default_memory_types': ['identity_fact', 'self_belief', 'goal', 'secret', 'voice_rule', 'callback_anchor'],
        },
    },
    'world': {
        'display_name': 'World',
        'category': 'setting',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'calendar_chronology', 'geography_environment', 'governance_law_diplomacy',
            'society_institutions', 'faith_magic_craft', 'travel_access_hazards',
            'peoples_species_creatures', 'economy_language', 'myths_truths', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'realm_type', 'world_role', 'calendar_summary', 'timeline_summary',
            'macro_geography', 'environmental_identity', 'governance_overview', 'law_overview',
            'society_overview', 'faith_and_belief_overview', 'magic_or_power_overview',
            'travel_systems_overview', 'people_and_species_overview', 'known_myths_vs_truth',
        ],
        'authoring_field_paths': [
            'fields.identity.realm_type',
            'fields.identity.world_role',
            'fields.calendar_chronology.calendar_summary',
            'fields.calendar_chronology.timeline_summary',
            'fields.geography_environment.macro_geography',
            'fields.geography_environment.environmental_identity',
            'fields.governance_law_diplomacy.governance_overview',
            'fields.governance_law_diplomacy.law_overview',
            'fields.society_institutions.society_overview',
            'fields.faith_magic_craft.faith_and_belief_overview',
            'fields.faith_magic_craft.magic_or_power_overview',
            'fields.travel_access_hazards.travel_systems_overview',
            'fields.peoples_species_creatures.people_and_species_overview',
            'fields.myths_truths.known_myths_vs_truth',
        ],
        'link_ownership': {
            'scope': ['universe_id'],
            'related': ['region_ids', 'city_ids', 'location_ids', 'organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'creature_ids', 'legend_ids', 'scenario_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['universe.worlds', 'region.world', 'city.world', 'location.world', 'scenario.world'],
        'runtime_surface': {
            'world_facts': ['summary', 'macro_geography', 'environmental_identity', 'society_overview', 'travel_systems_overview'],
            'canon': ['law_overview', 'magic_or_power_overview', 'known_myths_vs_truth'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'realm_type', 'world_role'],
            'fragment_candidates': [
                'summary', 'calendar_summary', 'timeline_summary', 'macro_geography',
                'environmental_identity', 'governance_overview', 'law_overview',
                'society_overview', 'faith_and_belief_overview', 'magic_or_power_overview',
                'travel_systems_overview', 'people_and_species_overview', 'known_myths_vs_truth',
            ],
            'default_memory_types': ['world_fact', 'canon_guard', 'callback_anchor'],
        },
    },
    'universe': {
        'display_name': 'Universe',
        'category': 'setting',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'cosmology', 'core_laws', 'timeline', 'world_scope',
            'species_systems', 'travel', 'systems_and_threats', 'truth_layers', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'universe_type', 'reality_model', 'cosmology_summary',
            'structure_of_existence', 'public_origin_story', 'universal_laws', 'metaphysical_rules',
            'time_rules', 'magic_or_power_source_model', 'timeline_summary', 'interworld_travel_status',
            'public_cosmology', 'canon_hierarchy_rules',
        ],
        'authoring_field_paths': [
            'fields.identity.universe_type',
            'fields.identity.reality_model',
            'fields.cosmology.cosmology_summary',
            'fields.cosmology.structure_of_existence',
            'fields.cosmology.public_origin_story',
            'fields.core_laws.universal_laws',
            'fields.core_laws.metaphysical_rules',
            'fields.core_laws.time_rules',
            'fields.core_laws.magic_or_power_source_model',
            'fields.timeline.timeline_summary',
            'fields.travel.interworld_travel_status',
            'fields.truth_layers.public_cosmology',
            'fields.truth_layers.canon_hierarchy_rules',
        ],
        'link_ownership': {
            'scope': ['primary_world_id'],
            'related': ['world_ids', 'cycle_ids', 'legend_ids', 'organization_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.universe', 'cycle.universe', 'legend.universe'],
        'runtime_surface': {
            'cosmology': ['summary', 'cosmology_summary', 'structure_of_existence', 'public_origin_story'],
            'canon': ['universal_laws', 'metaphysical_rules', 'time_rules', 'canon_hierarchy_rules'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'universe_type', 'reality_model'],
            'fragment_candidates': [
                'summary', 'cosmology_summary', 'structure_of_existence', 'public_origin_story',
                'universal_laws', 'metaphysical_rules', 'time_rules',
                'magic_or_power_source_model', 'timeline_summary', 'interworld_travel_status',
                'public_cosmology', 'canon_hierarchy_rules',
            ],
            'default_memory_types': ['world_fact', 'canon_guard'],
        },
    },
    'region': {
        'display_name': 'Region / Kingdom',
        'category': 'setting',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_scope', 'governance_ruling_power', 'geography_places',
            'travel_access_security', 'politics_law_diplomacy', 'society_culture_education',
            'faith_belief_ritual', 'economy_trade_language', 'mythic_hidden_legacy', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'region_type', 'governance_overview', 'regional_geography',
            'travel_access_overview', 'regional_law_overview', 'diplomacy_overview',
            'society_overview', 'cultural_identity', 'public_region_story', 'hidden_region_truth',
        ],
        'authoring_field_paths': [
            'fields.identity.region_type',
            'fields.governance_ruling_power.governance_overview',
            'fields.geography_places.regional_geography',
            'fields.travel_access_security.travel_access_overview',
            'fields.politics_law_diplomacy.regional_law_overview',
            'fields.politics_law_diplomacy.diplomacy_overview',
            'fields.society_culture_education.society_overview',
            'fields.society_culture_education.cultural_identity',
            'fields.mythic_hidden_legacy.public_region_story',
            'fields.mythic_hidden_legacy.hidden_region_truth',
        ],
        'link_ownership': {
            'scope': ['world_id', 'parent_region_id', 'capital_city_id', 'seat_location_id'],
            'related': ['city_ids', 'location_ids', 'organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'creature_ids', 'legend_ids', 'scenario_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.regions', 'city.region', 'location.region'],
        'runtime_surface': {
            'regional_facts': ['summary', 'regional_geography', 'cultural_identity', 'travel_access_overview'],
            'power': ['governance_overview', 'regional_law_overview', 'diplomacy_overview'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'region_type'],
            'fragment_candidates': ['summary', 'governance_overview', 'regional_geography', 'travel_access_overview', 'regional_law_overview', 'diplomacy_overview', 'society_overview', 'cultural_identity', 'public_region_story', 'hidden_region_truth'],
            'default_memory_types': ['world_fact', 'canon_guard'],
        },
    },
    'city': {
        'display_name': 'City / Settlement',
        'category': 'setting',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_access', 'governance_control', 'layout_districts',
            'access_safety_restrictions', 'society_local_culture', 'economy_trade_work',
            'faith_magic_ritual', 'organizations_power_blocs', 'creatures_environment_hazards',
            'rumors_truths', 'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'settlement_type', 'governance_overview', 'layout_overview',
            'access_notes', 'society_overview', 'local_culture_identity', 'public_city_story',
            'hidden_city_truth', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.settlement_type',
            'fields.governance_control.governance_overview',
            'fields.layout_districts.layout_overview',
            'fields.access_safety_restrictions.access_notes',
            'fields.society_local_culture.society_overview',
            'fields.society_local_culture.local_culture_identity',
            'fields.rumors_truths.public_city_story',
            'fields.rumors_truths.hidden_city_truth',
            'fields.scene_utility.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['world_id', 'region_id', 'parent_city_id', 'capital_of_region_id'],
            'related': ['location_ids', 'organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'creature_ids', 'legend_ids', 'scenario_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.cities', 'region.cities', 'location.city'],
        'runtime_surface': {
            'city_facts': ['summary', 'layout_overview', 'society_overview', 'local_culture_identity'],
            'scene_use': ['access_notes', 'public_city_story', 'scene_use_overview'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'settlement_type'],
            'fragment_candidates': ['summary', 'governance_overview', 'layout_overview', 'access_notes', 'society_overview', 'local_culture_identity', 'public_city_story', 'hidden_city_truth', 'scene_use_overview'],
            'default_memory_types': ['world_fact', 'location_state', 'callback_anchor'],
        },
    },
    'location': {
        'display_name': 'Location',
        'category': 'setting',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_scope', 'access_entry', 'spatial_layout', 'atmosphere_sensory',
            'rules_behavior_logic', 'hazards_pressure', 'present_powers_systems', 'public_hidden_truth',
            'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'location_type', 'anchor_type', 'access_notes', 'layout_overview',
            'atmosphere', 'rules_overview', 'hazards_overview', 'public_notes', 'hidden_truth', 'scene_uses',
        ],
        'authoring_field_paths': [
            'fields.identity.location_type',
            'fields.identity.anchor_type',
            'fields.access_entry.access_notes',
            'fields.spatial_layout.layout_overview',
            'fields.atmosphere_sensory.atmosphere',
            'fields.rules_behavior_logic.rules_overview',
            'fields.hazards_pressure.hazards_overview',
            'fields.public_hidden_truth.public_notes',
            'fields.public_hidden_truth.hidden_truth',
            'fields.scene_utility.scene_uses',
        ],
        'link_ownership': {
            'scope': ['universe_id', 'world_id', 'region_id', 'city_id', 'parent_location_id'],
            'related': ['character_ids', 'organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'creature_ids', 'legend_ids', 'scenario_ids', 'anchor_entity_id'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['city.locations', 'organization.base_location', 'artifact.location', 'scenario.location'],
        'runtime_surface': {
            'location_state': ['summary', 'layout_overview', 'atmosphere', 'rules_overview', 'hazards_overview'],
            'scene_use': ['access_notes', 'public_notes', 'hidden_truth', 'scene_uses'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'location_type', 'anchor_type'],
            'fragment_candidates': ['summary', 'access_notes', 'layout_overview', 'atmosphere', 'rules_overview', 'hazards_overview', 'public_notes', 'hidden_truth', 'scene_uses'],
            'default_memory_types': ['location_state', 'canon_guard', 'callback_anchor'],
        },
    },
    'organization': {
        'display_name': 'Organization / Faction',
        'category': 'group',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_scope', 'leadership_structure', 'beliefs_doctrine_mission',
            'public_hidden_truth', 'membership_recruitment', 'resources_assets_territory',
            'allies_rivals_enemies', 'local_role_influence_pressure', 'rituals_symbols_aesthetic',
            'internal_conflict_instability', 'story_roleplay_use', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'group_type', 'leadership_overview', 'core_beliefs', 'goals',
            'public_face', 'hidden_truth', 'membership_rules', 'resources_overview',
            'local_role_overview', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.group_type',
            'fields.leadership_structure.leadership_overview',
            'fields.beliefs_doctrine_mission.core_beliefs',
            'fields.beliefs_doctrine_mission.goals',
            'fields.public_hidden_truth.public_face',
            'fields.public_hidden_truth.hidden_truth',
            'fields.membership_recruitment.membership_rules',
            'fields.resources_assets_territory.resources_overview',
            'fields.local_role_influence_pressure.local_role_overview',
            'fields.story_roleplay_use.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['universe_id', 'world_id', 'region_id', 'city_id', 'base_location_id', 'parent_organization_id'],
            'related': ['leader_character_ids', 'member_character_ids', 'location_ids', 'ally_organization_ids', 'rival_organization_ids', 'artifact_ids', 'ritual_ids', 'legend_ids', 'scenario_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['character.organizations', 'location.organizations', 'organization.children'],
        'runtime_surface': {
            'identity': ['summary', 'group_type', 'leadership_overview', 'core_beliefs', 'goals'],
            'pressure': ['public_face', 'hidden_truth', 'membership_rules', 'resources_overview', 'local_role_overview'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'group_type'],
            'fragment_candidates': ['summary', 'leadership_overview', 'core_beliefs', 'goals', 'public_face', 'hidden_truth', 'membership_rules', 'resources_overview', 'local_role_overview', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'relationship_belief', 'canon_guard', 'story_hook'],
        },
    },
    'scenario': {
        'display_name': 'Scenario',
        'category': 'scene',
        'primary_label_key': 'title',
        'builder_sections': [
            'identity', 'placement_scene_anchor', 'premise_objective_stakes', 'opening_state_trigger_beat',
            'cast_roles_pov', 'forces_in_play', 'tone_emotional_logic_pressure', 'constraints_rules_boundaries',
            'hidden_layer_secrets_twist', 'scene_notes_gm_narrator', 'scene_runtime_use', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'format_hint', 'premise', 'objective', 'stakes', 'opening_beat',
            'pov_mode', 'pressure_profile', 'emotional_tone_overview', 'runtime_constraints',
            'hidden_twist', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.format_hint',
            'fields.premise_objective_stakes.premise',
            'fields.premise_objective_stakes.objective',
            'fields.premise_objective_stakes.stakes',
            'fields.opening_state_trigger_beat.opening_beat',
            'fields.cast_roles_pov.pov_mode',
            'fields.tone_emotional_logic_pressure.pressure_profile',
            'fields.tone_emotional_logic_pressure.emotional_tone_overview',
            'fields.constraints_rules_boundaries.runtime_constraints',
            'fields.hidden_layer_secrets_twist.hidden_twist',
            'fields.scene_runtime_use.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['universe_id', 'world_id', 'region_id', 'city_id', 'location_id'],
            'related': ['cast_character_ids', 'organization_ids', 'artifact_ids', 'ritual_ids', 'cycle_ids', 'legend_ids', 'creature_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.scenarios', 'location.scenarios', 'character.scenarios'],
        'runtime_surface': {
            'scene_packet': ['summary', 'premise', 'objective', 'stakes', 'opening_beat', 'pressure_profile', 'emotional_tone_overview', 'runtime_constraints', 'hidden_twist'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'format_hint'],
            'fragment_candidates': ['summary', 'premise', 'objective', 'stakes', 'opening_beat', 'pressure_profile', 'emotional_tone_overview', 'runtime_constraints', 'hidden_twist', 'scene_use_overview'],
            'default_memory_types': ['episodic_event', 'scene_pressure', 'callback_anchor', 'goal'],
        },
    },
    'artifact': {
        'display_name': 'Artifact / Weapon',
        'category': 'object',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'classification_state', 'placement_ownership', 'origin_provenance',
            'appearance_presence', 'function_effects_use', 'law_safety_restriction', 'dangers_pressure',
            'public_hidden_truth', 'bonds_associations_emotional_weight', 'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'artifact_type', 'rarity', 'state', 'appearance_summary',
            'effects', 'activation', 'costs', 'lawful_status', 'public_story', 'hidden_truth', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.artifact_type',
            'fields.classification_state.rarity',
            'fields.classification_state.state',
            'fields.appearance_presence.appearance_summary',
            'fields.function_effects_use.effects',
            'fields.function_effects_use.activation',
            'fields.function_effects_use.costs',
            'fields.law_safety_restriction.lawful_status',
            'fields.public_hidden_truth.public_story',
            'fields.public_hidden_truth.hidden_truth',
            'fields.scene_utility.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['world_id', 'region_id', 'city_id', 'location_id', 'current_holder_id', 'source_organization_id', 'source_ritual_id', 'source_legend_id'],
            'related': ['linked_character_ids', 'linked_organization_ids', 'linked_cycle_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['character.artifacts', 'location.artifacts', 'legend.artifacts'],
        'runtime_surface': {
            'identity': ['summary', 'artifact_type', 'rarity', 'state', 'appearance_summary'],
            'function': ['effects', 'activation', 'costs', 'lawful_status', 'public_story', 'hidden_truth'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'artifact_type', 'rarity', 'state'],
            'fragment_candidates': ['summary', 'appearance_summary', 'effects', 'activation', 'costs', 'lawful_status', 'public_story', 'hidden_truth', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'canon_guard', 'callback_anchor'],
        },
    },
    'ritual': {
        'display_name': 'Spell / Ritual / Technique',
        'category': 'system',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'classification_school_state', 'placement_source_tradition', 'function_effects',
            'requirements_conditions', 'activation_procedure', 'risks_costs_consequences',
            'law_ethics_restriction', 'users_access_transmission', 'public_hidden_truth',
            'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'practice_type', 'state', 'effect_summary', 'requirements',
            'activation', 'risks', 'lawful_status', 'public_story', 'hidden_truth', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.practice_type',
            'fields.classification_school_state.state',
            'fields.function_effects.effect_summary',
            'fields.requirements_conditions.requirements',
            'fields.activation_procedure.activation',
            'fields.risks_costs_consequences.risks',
            'fields.law_ethics_restriction.lawful_status',
            'fields.public_hidden_truth.public_story',
            'fields.public_hidden_truth.hidden_truth',
            'fields.scene_utility.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['world_id', 'region_id', 'location_id', 'source_organization_id', 'source_legend_id', 'source_artifact_id'],
            'related': ['linked_character_ids', 'linked_organization_ids', 'linked_artifact_ids', 'linked_cycle_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['location.rituals', 'artifact.rituals', 'legend.rituals'],
        'runtime_surface': {
            'identity': ['summary', 'practice_type', 'state'],
            'function': ['effect_summary', 'requirements', 'activation', 'risks', 'lawful_status', 'public_story', 'hidden_truth'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'practice_type', 'state'],
            'fragment_candidates': ['summary', 'effect_summary', 'requirements', 'activation', 'risks', 'lawful_status', 'public_story', 'hidden_truth', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'canon_guard'],
        },
    },
    'cycle': {
        'display_name': 'Cycle / Condition / System',
        'category': 'system',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'scope_reach', 'affected_targets', 'trigger_cadence_onset', 'stages_progression',
            'effects_outcomes', 'safeguards_resistance_management', 'law_ethics_cultural_handling',
            'public_hidden_truth', 'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'system_type', 'scope_type', 'trigger', 'cadence', 'effects',
            'safeguards', 'public_story', 'hidden_truth', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.system_type',
            'fields.scope_reach.scope_type',
            'fields.trigger_cadence_onset.trigger',
            'fields.trigger_cadence_onset.cadence',
            'fields.effects_outcomes.effects',
            'fields.safeguards_resistance_management.safeguards',
            'fields.public_hidden_truth.public_story',
            'fields.public_hidden_truth.hidden_truth',
            'fields.scene_utility.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['universe_id', 'world_id', 'region_id', 'location_id', 'source_organization_id', 'source_legend_id'],
            'related': ['linked_character_ids', 'linked_creature_ids', 'linked_ritual_ids', 'linked_artifact_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['universe.cycles', 'world.cycles', 'location.cycles'],
        'runtime_surface': {
            'identity': ['summary', 'system_type', 'scope_type', 'trigger', 'cadence'],
            'effects': ['effects', 'safeguards', 'public_story', 'hidden_truth'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'system_type', 'scope_type', 'trigger', 'cadence'],
            'fragment_candidates': ['summary', 'effects', 'safeguards', 'public_story', 'hidden_truth', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'canon_guard', 'callback_anchor'],
        },
    },
    'creature': {
        'display_name': 'Creature / Animal / Fauna',
        'category': 'actor',
        'primary_label_key': 'name',
        'builder_sections': [
            'identity', 'placement_habitat_range', 'sentience_social_pattern', 'physicality_appearance_presence',
            'diet_behavior_instinct', 'danger_threat_utility', 'domestication_bonding_handling',
            'magic_system_special_traits', 'public_hidden_truth', 'role_in_world_society_scene', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'category', 'sentience', 'appearance_summary',
            'diet_and_behavior', 'danger_level', 'public_story', 'hidden_truth',
            'world_role_notes', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.category',
            'fields.sentience_social_pattern.sentience',
            'fields.physicality_appearance_presence.appearance_summary',
            'fields.diet_behavior_instinct.diet_and_behavior',
            'fields.danger_threat_utility.danger_level',
            'fields.public_hidden_truth.public_story',
            'fields.public_hidden_truth.hidden_truth',
            'fields.role_in_world_society_scene.world_role_notes',
            'fields.role_in_world_society_scene.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['world_id', 'region_id', 'location_id', 'source_legend_id', 'source_cycle_id', 'source_organization_id'],
            'related': ['linked_character_ids', 'linked_ritual_ids', 'linked_location_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.creatures', 'location.creatures', 'legend.creatures'],
        'runtime_surface': {
            'identity': ['summary', 'category', 'sentience', 'appearance_summary', 'diet_and_behavior', 'danger_level'],
            'scene_use': ['world_role_notes', 'scene_use_overview', 'public_story', 'hidden_truth'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'category', 'sentience'],
            'fragment_candidates': ['summary', 'appearance_summary', 'diet_and_behavior', 'danger_level', 'public_story', 'hidden_truth', 'world_role_notes', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'canon_guard'],
        },
    },
    'legend': {
        'display_name': 'Legend',
        'category': 'lore',
        'primary_label_key': 'title',
        'builder_sections': [
            'identity', 'scope_placement_anchor', 'public_hidden_versions', 'believers_suppressors_keepers',
            'linked_entities_forces', 'consequences_stakes', 'cultural_role_function',
            'evidence_fragments_contradictions', 'public_story_texture', 'scene_utility', 'rich_authoring',
        ],
        'canonical_fields': [
            'display_label', 'summary', 'legend_type', 'truth_status', 'scope_type',
            'public_version', 'hidden_version', 'consequences_if_true', 'scene_use_overview',
        ],
        'authoring_field_paths': [
            'fields.identity.legend_type',
            'fields.identity.truth_status',
            'fields.scope_placement_anchor.scope_type',
            'fields.public_hidden_versions.public_version',
            'fields.public_hidden_versions.hidden_version',
            'fields.consequences_stakes.consequences_if_true',
            'fields.scene_utility.scene_use_overview',
        ],
        'link_ownership': {
            'scope': ['universe_id', 'world_id', 'region_id', 'location_id'],
            'related': ['linked_character_ids', 'linked_organization_ids', 'linked_artifact_ids', 'linked_ritual_ids', 'linked_cycle_ids', 'linked_creature_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['universe.legends', 'world.legends', 'location.legends', 'artifact.legends'],
        'runtime_surface': {
            'legend': ['summary', 'legend_type', 'truth_status', 'public_version', 'hidden_version', 'consequences_if_true'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'legend_type', 'truth_status', 'scope_type'],
            'fragment_candidates': ['summary', 'public_version', 'hidden_version', 'consequences_if_true', 'scene_use_overview'],
            'default_memory_types': ['semantic_fact', 'canon_guard', 'callback_anchor'],
        },
    },
    'pack': {
        'display_name': 'Pack',
        'category': 'bundle',
        'primary_label_key': 'name',
        'builder_sections': ['identity', 'rich_authoring'],
        'canonical_fields': ['display_label', 'summary', 'theme'],
        'authoring_field_paths': ['fields.identity.theme'],
        'link_ownership': {
            'scope': ['world_id'],
            'related': ['scenario_ids', 'character_ids', 'location_ids'],
        },
        'edge_sections': [],
        'derived_reverse_links': ['world.packs', 'scenario.packs', 'character.packs'],
        'runtime_surface': {
            'bundle': ['summary', 'theme'],
        },
        'memory_compile': {
            'structured_only': ['display_label', 'theme'],
            'fragment_candidates': ['summary'],
            'default_memory_types': ['semantic_fact', 'callback_anchor'],
        },
    },
}


def build_canonical_entity_map() -> dict[str, dict[str, Any]]:
    return deepcopy(ROLEPLAY_V2_CANONICAL_ENTITY_MAP)


