from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from .config import APP_DIR, ROOT_DIR
from .shared_data_paths import library_data_path, studio_data_path

IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.webp', '.bmp'}
FORMAT_TO_SUFFIX = {'JPEG': '.jpg', 'PNG': '.png', 'WEBP': '.webp', 'BMP': '.bmp'}
MAX_UPLOAD_BYTES = 25 * 1024 * 1024
MAX_TEMP_AGE_HOURS = 24 * 7

USER_DATA_DIR = studio_data_path('', legacy_rel='')
SETTINGS_PATH = studio_data_path('neo_studio_settings.json', legacy_rel='neo_studio_settings.json', default_json={})
NEO_LIBRARY_SETTINGS_PATH = library_data_path('neo_library_settings.json', legacy_rel='neo_library_settings.json', default_json={})
DEFAULT_ROOT = ROOT_DIR / 'neo_library_data'
TEMP_DIR = APP_DIR / 'temp_uploads'

BUILTIN_CAPTION_PRESETS: Dict[str, Dict[str, Any]] = {
    'Tags': {
        'prompt_style': 'Stable Diffusion Prompt',
        'caption_length': 'medium',
        'custom_prompt': '',
        'max_new_tokens': 128,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Descriptive': {
        'prompt_style': 'Descriptive',
        'caption_length': 'long',
        'custom_prompt': '',
        'max_new_tokens': 480,
        'temperature': 0.3,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Literal Tags': {
        'prompt_style': 'Custom',
        'caption_length': 'short',
        'custom_prompt': 'Describe only what is clearly visible. Return one single line of comma-separated Stable Diffusion tags. Count people exactly. Do not add any person not visible. Do not guess gender unless clear. If unclear, use person or adult. No numbering. No full sentences. No repetition.',
        'max_new_tokens': 72,
        'temperature': 0.15,
        'top_p': 0.8,
        'top_k': 20,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Literal Descriptive': {
        'prompt_style': 'Custom',
        'caption_length': 'medium',
        'custom_prompt': 'Describe only what is directly visible in plain factual prose. Keep it literal. Do not guess identity, story, or relationships. One short paragraph only.',
        'max_new_tokens': 140,
        'temperature': 0.15,
        'top_p': 0.85,
        'top_k': 30,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Dataset Short': {
        'prompt_style': 'Stable Diffusion Prompt',
        'caption_length': 'short',
        'custom_prompt': '',
        'max_new_tokens': 96,
        'temperature': 0.15,
        'top_p': 0.85,
        'top_k': 30,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Dataset Detailed': {
        'prompt_style': 'Stable Diffusion Prompt',
        'caption_length': 'long',
        'custom_prompt': '',
        'max_new_tokens': 180,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
    'Anime Bias': {
        'prompt_style': 'Stable Diffusion Prompt',
        'caption_length': 'medium',
        'custom_prompt': '',
        'max_new_tokens': 128,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Anime',
        'kind': 'builtin',
    },
    'Realistic Bias': {
        'prompt_style': 'Stable Diffusion Prompt',
        'caption_length': 'medium',
        'custom_prompt': '',
        'max_new_tokens': 128,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Realistic',
        'kind': 'builtin',
    },
    'Custom': {
        'prompt_style': 'Custom',
        'caption_length': 'any',
        'custom_prompt': '',
        'max_new_tokens': 160,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'prefix': '',
        'suffix': '',
        'output_style': 'Auto (match input)',
        'kind': 'builtin',
    },
}

BUILTIN_PROMPT_PRESETS: Dict[str, Dict[str, Any]] = {
    'SD Tags Tight': {
        'style': 'Stable Diffusion Prompt',
        'custom_instructions': 'Return concise comma-separated visual tags only. Keep it very compact. No prose.',
        'max_tokens': 110,
        'temperature': 0.18,
        'top_p': 0.85,
        'top_k': 30,
        'kind': 'builtin',
    },
    'SD Tags': {
        'style': 'Stable Diffusion Prompt',
        'custom_instructions': 'Return concise comma-separated visual tags only. Keep it compact and production-ready. Avoid long prose.',
        'max_tokens': 160,
        'temperature': 0.2,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'SD Tags Rich': {
        'style': 'Stable Diffusion Prompt',
        'custom_instructions': 'Return richer comma-separated visual tags. Add useful detail but stay tag-based and concise.',
        'max_tokens': 220,
        'temperature': 0.24,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'Descriptive': {
        'style': 'Descriptive',
        'custom_instructions': 'Write one complete natural-language prompt with clear visual details. Avoid list formatting and tag spam. End cleanly.',
        'max_tokens': 500,
        'temperature': 0.35,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'Descriptive Compact': {
        'style': 'Descriptive',
        'custom_instructions': 'Write one complete but compact natural-language prompt. Keep it focused and avoid over-describing minor details.',
        'max_tokens': 280,
        'temperature': 0.3,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'Cinematic': {
        'style': 'Descriptive',
        'custom_instructions': 'Emphasize framing, mood, lighting, lens feel, camera position, and cinematic atmosphere without turning into purple prose.',
        'max_tokens': 420,
        'temperature': 0.42,
        'top_p': 0.92,
        'top_k': 50,
        'kind': 'builtin',
    },
    'Rewrite / Clean': {
        'style': 'Custom',
        'custom_instructions': 'Rewrite the prompt cleanly, preserve meaning, remove contradictions, remove repetition, and keep only the strongest useful details.',
        'max_tokens': 260,
        'temperature': 0.22,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'Style Convert': {
        'style': 'Style Convert',
        'custom_instructions': 'If the input looks like prose, convert it to concise Stable Diffusion tags. If the input looks like tags, convert it to one clean natural-language prompt. Preserve visible content and do not invent new elements.',
        'max_tokens': 260,
        'temperature': 0.22,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
    'Custom': {
        'style': 'Custom',
        'custom_instructions': '',
        'max_tokens': 220,
        'temperature': 0.35,
        'top_p': 0.9,
        'top_k': 40,
        'kind': 'builtin',
    },
}
